descriptor_extension: yml
package:
  description: service comprising an iperf, firewall, tcpdump and vtc
  maintainer: Luis Conceicao, UBIWHERE
  name: p-complex
  vendor: eu.sonata-nfv.eu
  version: '0.1'
version: '0.5'
